use_frameworks!

platform :ios, '10.0'

target 'QRScan_Example' do
  pod 'QRScan', :path => '../'

  target 'QRScan_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
